### ISSUE TITLE
[Input] placeholderの色を変更したい

### ISSUE THREAD

**Issue by overgoro56** [visits-works/visits-style#19]
```css 
 ::-webkit-input-placeholder { /* WebKit, Blink, Edge */
    color:#adadad;
  }
  :-ms-input-placeholder { /* Internet Explorer 10-11 */
    color:#adadad;
  }
  ::placeholder{ /* Others */
    color:#adadad
  }
```
