### ISSUE TITLE
[Button] disabledの色を変更したい

### ISSUE THREAD

**Issue by overgoro56** [visits-works/visits-style#20]
```css
  button:disabled {
    background: #b7bec5 !important;
    color: #ffffff !important;
  }
```
